# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Login.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.setWindowModality(QtCore.Qt.ApplicationModal)
        Login.resize(266, 172)
        font = QtGui.QFont()
        font.setFamily("Arial")
        Login.setFont(font)
        Login.setModal(False)
        self.LoginConfirmbtn = QtWidgets.QPushButton(Login)
        self.LoginConfirmbtn.setGeometry(QtCore.QRect(70, 90, 75, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.LoginConfirmbtn.setFont(font)
        self.LoginConfirmbtn.setObjectName("LoginConfirmbtn")
        self.pushButton_2 = QtWidgets.QPushButton(Login)
        self.pushButton_2.setGeometry(QtCore.QRect(160, 90, 75, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.IDPWCheck = QtWidgets.QCheckBox(Login)
        self.IDPWCheck.setGeometry(QtCore.QRect(90, 130, 151, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.IDPWCheck.setFont(font)
        self.IDPWCheck.setTabletTracking(False)
        self.IDPWCheck.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.IDPWCheck.setChecked(True)
        self.IDPWCheck.setTristate(False)
        self.IDPWCheck.setObjectName("IDPWCheck")
        self.layoutWidget = QtWidgets.QWidget(Login)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 11, 231, 24))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.LoginID = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.LoginID.setFont(font)
        self.LoginID.setMaxLength(16)
        self.LoginID.setObjectName("LoginID")
        self.horizontalLayout.addWidget(self.LoginID)
        self.layoutWidget1 = QtWidgets.QWidget(Login)
        self.layoutWidget1.setGeometry(QtCore.QRect(11, 51, 231, 24))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.LoginPW = QtWidgets.QLineEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.LoginPW.setFont(font)
        self.LoginPW.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.LoginPW.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.LoginPW.setMaxLength(16)
        self.LoginPW.setEchoMode(QtWidgets.QLineEdit.Password)
        self.LoginPW.setObjectName("LoginPW")
        self.horizontalLayout_2.addWidget(self.LoginPW)

        self.retranslateUi(Login)
        self.pushButton_2.clicked.connect(self.LoginPW.clear)
        self.pushButton_2.clicked.connect(self.LoginID.clear)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "登入"))
        self.LoginConfirmbtn.setText(_translate("Login", "確認"))
        self.pushButton_2.setText(_translate("Login", "清除"))
        self.IDPWCheck.setText(_translate("Login", "是否記住帳號密碼"))
        self.label.setText(_translate("Login", "帳號:"))
        self.label_2.setText(_translate("Login", "密碼:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login = QtWidgets.QDialog()
    ui = Ui_Login()
    ui.setupUi(Login)
    Login.show()
    sys.exit(app.exec_())

