# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CapitalAPI(object):
    def setupUi(self, CapitalAPI):
        CapitalAPI.setObjectName("CapitalAPI")
        CapitalAPI.setWindowModality(QtCore.Qt.NonModal)
        CapitalAPI.resize(1026, 571)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        CapitalAPI.setFont(font)
        self.centralwidget = QtWidgets.QWidget(CapitalAPI)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.South)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.GL = QtWidgets.QGridLayout()
        self.GL.setObjectName("GL")
        self.horizontalLayout.addLayout(self.GL)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.commodityline = QtWidgets.QLineEdit(self.tab)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.commodityline.setFont(font)
        self.commodityline.setObjectName("commodityline")
        self.verticalLayout.addWidget(self.commodityline)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.TDetailbtn = QtWidgets.QPushButton(self.tab)
        self.TDetailbtn.setObjectName("TDetailbtn")
        self.horizontalLayout_2.addWidget(self.TDetailbtn)
        self.commoditybtn = QtWidgets.QPushButton(self.tab)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.commoditybtn.setFont(font)
        self.commoditybtn.setObjectName("commoditybtn")
        self.horizontalLayout_2.addWidget(self.commoditybtn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.DomTable = QtWidgets.QTableWidget(self.tab)
        self.DomTable.setAlternatingRowColors(True)
        self.DomTable.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.DomTable.setRowCount(27)
        self.DomTable.setColumnCount(3)
        self.DomTable.setObjectName("DomTable")
        self.DomTable.horizontalHeader().setVisible(False)
        self.DomTable.horizontalHeader().setCascadingSectionResizes(True)
        self.DomTable.horizontalHeader().setMinimumSectionSize(24)
        self.DomTable.verticalHeader().setVisible(False)
        self.DomTable.verticalHeader().setCascadingSectionResizes(True)
        self.DomTable.verticalHeader().setMinimumSectionSize(12)
        self.verticalLayout.addWidget(self.DomTable)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_3.addWidget(self.pushButton)
        self.pushButton_3 = QtWidgets.QPushButton(self.tab)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_3.addWidget(self.pushButton_3)
        self.verticalLayout_3.setStretch(0, 2)
        self.verticalLayout_3.setStretch(1, 1)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.spinBox_2 = QtWidgets.QSpinBox(self.tab)
        self.spinBox_2.setObjectName("spinBox_2")
        self.verticalLayout_2.addWidget(self.spinBox_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_4.addWidget(self.pushButton_2)
        self.pushButton_4 = QtWidgets.QPushButton(self.tab)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_4.addWidget(self.pushButton_4)
        self.verticalLayout_4.setStretch(0, 2)
        self.verticalLayout_4.setStretch(1, 1)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 2)
        self.horizontalLayout_3.setStretch(2, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_5.addWidget(self.pushButton_6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.spinBox = QtWidgets.QSpinBox(self.tab)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_4.addWidget(self.spinBox)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.tab)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_5.addWidget(self.pushButton_5)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout.setStretch(3, 30)
        self.verticalLayout.setStretch(4, 3)
        self.verticalLayout.setStretch(5, 1)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout.setStretch(0, 5)
        self.horizontalLayout.setStretch(1, 1)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tableView = QtWidgets.QTableView(self.tab_2)
        self.tableView.setObjectName("tableView")
        self.verticalLayout_5.addWidget(self.tableView)
        self.tableView_2 = QtWidgets.QTableView(self.tab_2)
        self.tableView_2.setObjectName("tableView_2")
        self.verticalLayout_5.addWidget(self.tableView_2)
        self.horizontalLayout_6.addLayout(self.verticalLayout_5)
        self.Right_TB = QtWidgets.QTableView(self.tab_2)
        self.Right_TB.setAlternatingRowColors(True)
        self.Right_TB.horizontalHeader.setAutoFillBackground
        self.Right_TB.setObjectName("Right_TB")
        self.tableitem=self.Right_TB.sets
        self.horizontalLayout_6.addWidget(self.Right_TB)
        self.horizontalLayout_6.setStretch(0, 1)
        self.horizontalLayout_6.setStretch(1, 1)
        self.gridLayout.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_3.addWidget(self.tabWidget, 0, 0, 1, 1)
        CapitalAPI.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CapitalAPI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1026, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        CapitalAPI.setMenuBar(self.menubar)
        self.statusBar = QtWidgets.QStatusBar(CapitalAPI)
        self.statusBar.setObjectName("statusBar")
        CapitalAPI.setStatusBar(self.statusBar)
        self.toolBar = QtWidgets.QToolBar(CapitalAPI)
        self.toolBar.setObjectName("toolBar")
        CapitalAPI.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionLogin = QtWidgets.QAction(CapitalAPI)
        self.actionLogin.setObjectName("actionLogin")
        self.SysDetail = QtWidgets.QAction(CapitalAPI)
        self.SysDetail.setObjectName("SysDetail")
        self.Connectbtn = QtWidgets.QAction(CapitalAPI)
        self.Connectbtn.setObjectName("Connectbtn")
        self.Disconnectbtn = QtWidgets.QAction(CapitalAPI)
        self.Disconnectbtn.setObjectName("Disconnectbtn")
        self.menu_3.addAction(self.actionLogin)
        self.menu_3.addSeparator()
        self.menu_4.addSeparator()
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())
        self.toolBar.addAction(self.SysDetail)
        self.toolBar.addAction(self.Connectbtn)
        self.toolBar.addAction(self.Disconnectbtn)

        self.retranslateUi(CapitalAPI)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(CapitalAPI)

    def retranslateUi(self, CapitalAPI):
        _translate = QtCore.QCoreApplication.translate
        CapitalAPI.setWindowTitle(_translate("CapitalAPI", "群益API"))
        self.label.setText(_translate("CapitalAPI", "商品"))
        self.commodityline.setText(_translate("CapitalAPI", "TX00"))
        self.TDetailbtn.setText(_translate("CapitalAPI", "交易明細"))
        self.commoditybtn.setText(_translate("CapitalAPI", "OK"))
        self.pushButton.setText(_translate("CapitalAPI", "市價買"))
        self.pushButton_3.setText(_translate("CapitalAPI", "限價買"))
        self.label_2.setText(_translate("CapitalAPI", "未平倉"))
        self.label_3.setText(_translate("CapitalAPI", "損益"))
        self.pushButton_2.setText(_translate("CapitalAPI", "市價賣"))
        self.pushButton_4.setText(_translate("CapitalAPI", "限價賣"))
        self.pushButton_6.setText(_translate("CapitalAPI", "一鍵刪單"))
        self.label_4.setText(_translate("CapitalAPI", "口數設定:"))
        self.pushButton_5.setText(_translate("CapitalAPI", "一鍵平倉"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("CapitalAPI", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("CapitalAPI", "期權帳務"))
        self.menu.setTitle(_translate("CapitalAPI", "檔案"))
        self.menu_2.setTitle(_translate("CapitalAPI", "檢視"))
        self.menu_3.setTitle(_translate("CapitalAPI", "功能"))
        self.menu_4.setTitle(_translate("CapitalAPI", "說明"))
        self.toolBar.setWindowTitle(_translate("CapitalAPI", "toolBar"))
        self.actionLogin.setText(_translate("CapitalAPI", "登入"))
        self.SysDetail.setText(_translate("CapitalAPI", "系統訊息"))
        self.SysDetail.setToolTip(_translate("CapitalAPI", "API系統訊息"))
        self.Connectbtn.setText(_translate("CapitalAPI", "報價連線"))
        self.Connectbtn.setToolTip(_translate("CapitalAPI", "建立報價連線回報機制"))
        self.Disconnectbtn.setText(_translate("CapitalAPI", "報價清除"))
        self.Disconnectbtn.setToolTip(_translate("CapitalAPI", "斷開或情除報價連線狀態"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CapitalAPI = QtWidgets.QMainWindow()
    ui = Ui_CapitalAPI()
    ui.setupUi(CapitalAPI)
    CapitalAPI.show()
    sys.exit(app.exec_())

